### ISSUE TITLE
Feature request: "Count-Up" for past events

### ISSUE THREAD

**Issue by DuschdrBabbe** [jack-blackson/ioBroker.countdown#74]
Countdown also in past...
Count Years Days Hours also in the past....

EDIT*: just count workdays (without weekends and puplic hollidays)

**Comment by jack-blackson** [comment]
Hello! Part of this is now done - the countUp feature is available in version 2.1.0, in the latest channel. What is not done is just counting workdays - there I don't know how to handle that, because where to take the calendar from. This is a really very regional topic, and I guess will lead to a lot of wrong results.
